version: '3'

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=encuestas_whats_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3308:3306"
  web:
    build: .
    command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8010:8000"
    depends_on:
      - db

volumes:
  mariadb_data: