# Generated by Django 4.1.3 on 2022-11-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_encuestas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
