# Generated by Django 4.1.3 on 2022-11-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_encuestas_app', '0002_encuesta_bitly_url_encuesta_long_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='id',
            field=models.UUIDField(default='0b5d0acacfe64d5bac94781e6f9510f9', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='0b5d0acacfe64d5bac94781e6f9510f9', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.UUIDField(default='0b5d0acacfe64d5bac94781e6f9510f9', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='id',
            field=models.UUIDField(default='0b5d0acacfe64d5bac94781e6f9510f9', primary_key=True, serialize=False, unique=True),
        ),
    ]
