# Generated by Django 4.1.3 on 2022-11-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_encuestas_app', '0003_opcion_pregunta_encuesta_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigo',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='codigo',
            unique_together={('codigo', 'id')},
        ),
    ]
